import { z } from "zod";
import { BrowserActionSchema } from "./actions";

/**
 * Intent Classification Schema per §9 & docs/CAPABILITIES.md
 */
export const IntentTypeSchema = z.enum([
  "SUPPORTED",
  "NEEDS_CLARIFICATION",
  "REQUIRES_AUTH",
  "UNSUPPORTED",
  "BLOCKED",
]);
export type IntentType = z.infer<typeof IntentTypeSchema>;

export const IntentClassificationSchema = z.object({
  classification: IntentTypeSchema,
  confidence: z.number().min(0).max(1).default(1.0),
  rationale: z.string().min(1, "Rationale explaining the classification decision is required"),
  targetDomains: z.array(z.string()).default([]),
  clarificationQuestion: z.string().nullable().optional(),
  suggestedAction: z.string().nullable().optional(),
  requiredCapabilities: z.array(z.string()).default([]),
});
export type IntentClassification = z.infer<typeof IntentClassificationSchema>;

/**
 * Action Plan Schema per skills/browser-agent.md
 * Structured sequence of tool calls generated by Gemini Planner
 */
export const PlannedStepSchema = z.object({
  stepNumber: z.number().int().positive(),
  action: BrowserActionSchema,
  rationale: z.string(),
  isOptional: z.boolean().optional().default(false),
  checkpointScreenshot: z.boolean().optional().default(false),
});
export type PlannedStep = z.infer<typeof PlannedStepSchema>;

export const ActionPlanSchema = z.object({
  goal: z.string().min(1, "Goal description is required"),
  targetDomains: z.array(z.string()).min(1, "At least one target domain must be identified"),
  steps: z.array(PlannedStepSchema).min(1, "ActionPlan must contain at least one planned step"),
  expectedOutputDescription: z.string().optional(),
  maxStepsBudget: z.number().int().min(1).max(25).optional().default(15),
  estimatedDurationSeconds: z.number().positive().optional().default(15),
  rationale: z.string().optional(),
});
export type ActionPlan = z.infer<typeof ActionPlanSchema>;
export type ActionPlanInput = z.input<typeof ActionPlanSchema>;

/**
 * Safely parses and normalizes allowedDomains from diverse formats:
 * - JSON string: '["news.ycombinator.com", "github.com"]'
 * - Comma-separated string: 'news.ycombinator.com, github.com'
 * - String array: ['news.ycombinator.com']
 * - Null / undefined / empty string: []
 */
export function parseAllowedDomains(input: unknown): string[] {
  if (!input) return [];

  if (Array.isArray(input)) {
    return Array.from(
      new Set(
        input
          .filter((item): item is string => typeof item === "string")
          .map((s) => s.trim().toLowerCase())
          .filter(Boolean)
      )
    );
  }

  if (typeof input === "string") {
    const trimmed = input.trim();
    if (!trimmed || trimmed === "[]") return [];

    if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
      try {
        const parsed = JSON.parse(trimmed);
        if (Array.isArray(parsed)) {
          return Array.from(
            new Set(
              parsed
                .filter((item): item is string => typeof item === "string")
                .map((s) => s.trim().toLowerCase())
                .filter(Boolean)
            )
          );
        }
      } catch {
        // Fallback to comma-delimited
      }
    }

    return Array.from(
      new Set(
        trimmed
          .split(",")
          .map((d) => d.trim().toLowerCase())
          .filter(Boolean)
      )
    );
  }

  return [];
}

/**
 * Standard Job Creation Request Schema
 */
export const CreateJobRequestSchema = z.object({
  prompt: z.string().min(1, "Task prompt is required").max(2000, "Prompt must be under 2000 characters"),
  userId: z.string().optional(),
  allowedDomains: z.preprocess((val) => parseAllowedDomains(val), z.array(z.string())).optional().default([]),
  maxStepsBudget: z.number().int().min(1).max(25).optional().default(15),
  apiKey: z.string().optional(),
});
export type CreateJobRequest = z.infer<typeof CreateJobRequestSchema>;

