import { z } from "zod";
import { BrowserActionSchema } from "./actions";

/**
 * Intent Classification Schema per §9 & docs/CAPABILITIES.md
 */
export const IntentTypeSchema = z.enum([
  "SUPPORTED",
  "NEEDS_CLARIFICATION",
  "REQUIRES_AUTH",
  "UNSUPPORTED",
  "BLOCKED",
]);
export type IntentType = z.infer<typeof IntentTypeSchema>;

export const IntentClassificationSchema = z.object({
  classification: IntentTypeSchema,
  confidence: z.number().min(0).max(1).default(1.0),
  rationale: z.string().min(1, "Rationale explaining the classification decision is required"),
  targetDomains: z.array(z.string()).default([]),
  clarificationQuestion: z.string().nullable().optional(),
  suggestedAction: z.string().nullable().optional(),
  requiredCapabilities: z.array(z.string()).default([]),
});
export type IntentClassification = z.infer<typeof IntentClassificationSchema>;

/**
 * Action Plan Schema per skills/browser-agent.md
 * Structured sequence of tool calls generated by Gemini Planner
 */
export const PlannedStepSchema = z.object({
  stepNumber: z.number().int().positive(),
  action: BrowserActionSchema,
  rationale: z.string(),
  isOptional: z.boolean().optional().default(false),
  checkpointScreenshot: z.boolean().optional().default(false),
});
export type PlannedStep = z.infer<typeof PlannedStepSchema>;

export const ActionPlanSchema = z.object({
  goal: z.string().min(1, "Goal description is required"),
  targetDomains: z.array(z.string()).min(1, "At least one target domain must be identified"),
  steps: z.array(PlannedStepSchema).min(1, "ActionPlan must contain at least one planned step"),
  expectedOutputDescription: z.string().optional(),
  maxStepsBudget: z.number().int().min(1).max(25).optional().default(15),
  estimatedDurationSeconds: z.number().positive().optional().default(15),
  rationale: z.string().optional(),
});
export type ActionPlan = z.infer<typeof ActionPlanSchema>;
export type ActionPlanInput = z.input<typeof ActionPlanSchema>;
